#!/usr/bin/python

"""
http://www.multipath-tcp.org/
http://blog.multipath-tcp.org/blog/html/2014/09/16/recommended_multipath_tcp_configuration.html
http://blog.multipath-tcp.org/blog/html/2015/02/06/mptcptrace_demo_experiment_five.html

http://mininet.org/api/classmininet_1_1net_1_1Mininet.html
https://github.com/mininet/mininet/blob/master/mininet/node.py

https://www.wireshark.org/docs/man-pages/tshark.html
https://www.wireshark.org/docs/dfref/t/tcp.html
http://www.packetlevel.ch/html/tcpdumpf.html
tshark -G | grep Multipath

https://iperf.fr/iperf-doc.php
https://github.com/ouya/iperf/

https://docs.python.org/2/library/xml.etree.elementtree.html
http://effbot.org/downloads#elementtree


https://github.com/remichauvenne/mptcp-model-thesis

"""

"""
questions:
 - what is a mininet.controller (c0)? why it's not working without that?
 - why are host trend to be behind a switch?
 - how to meansure/monitor bandwith/delay?
 - iperf 'Connection refused' sometimes...
 - double delay on the first ping
 - iperf freeze if swith's interface turn down, but good handover if host's intf down
 - mininet learn between runs, ping breaks arp/handover ?!?!?!?!?!?!?!???
 - 

Notes:
 - run program on a host: run long process at background and pipe it's output to file, so other short processes can run meanwhile (sendCmd don't block the caller script, but sets waiting to True)

"""


### CONFIGURATIONS ###

#sysctl net.mptcp
#sysctl net | grep congestion
#sysctl net | grep 'mptcp\|congestion'

"congestion controls:"
#os.system('sysctl -w net.ipv4.tcp_congestion_control=cubic ')
#os.system('modprobe mptcp_coupled && sysctl -w net.ipv4.tcp_congestion_control=lia ')
#os.system('modprobe mptcp_olia && sysctl -w net.ipv4.tcp_congestion_control=olia ')
#os.system('modprobe mptcp_wvegas && sysctl -w net.ipv4.tcp_congestion_control=wvegas ')
#os.system('modprobe mptcp_balia && sysctl -w net.ipv4.tcp_congestion_control=balia ')

"path-managers:"
#os.system('sysctl -w net.mptcp.mptcp_path_manager=default ')
#os.system('sysctl -w net.mptcp.mptcp_path_manager=fullmesh ')
#os.system('echo 1 | sudo tee /sys/module/mptcp_fullmesh/parameters/num_subflows')
#os.system('modprobe mptcp_ndiffports && sysctl -w net.mptcp.mptcp_path_manager=ndiffports ')
#os.system('echo 1 | sudo tee /sys/module/mptcp_ndiffports/parameters/num_subflows')
#os.system('modprobe mptcp_binder && sysctl -w net.mptcp.mptcp_path_manager=binder ')

"scheduler:"
#os.system('sysctl -w net.mptcp.mptcp_scheduler=default ')
#os.system('modprobe mptcp_rr && sysctl -w net.mptcp.mptcp_scheduler=roundrobin ')
#os.system('echo 1 | sudo tee /sys/module/mptcp_rr/parameters/num_segments')
#os.system('echo Y | sudo tee /sys/module/mptcp_rr/parameters/cwnd_limited')
#os.system('modprobe mptcp_redundant && sysctl -w net.mptcp.mptcp_scheduler=redundant ')


import time
import os
import sys
import re
import xml.etree.ElementTree
from mininet.net import Mininet
from mininet.link import TCLink

test_bandwith = True
capture_mptcp_headers = False
cut_a_link = True
add_a_link = True
max_queue_size = 100
use_custom_meter = False
test_duration = 24 # seconds


net = Mininet( cleanup=True )

h1 = net.addHost( 'h1', ip='10.0.1.1')
h2 = net.addHost( 'h2', ip='10.0.2.1')

s3 = net.addSwitch( 's3' )

c0 = net.addController( 'c0' )

net.addLink( h1, s3, cls=TCLink , bw=5, delay='50ms', max_queue_size=max_queue_size )
net.addLink( h1, s3, cls=TCLink , bw=10, delay='1ms', max_queue_size=max_queue_size )
net.addLink( h2, s3, cls=TCLink , bw=50, delay='1ms', max_queue_size=max_queue_size )
net.addLink( h2, s3, cls=TCLink , bw=50, delay='1ms', max_queue_size=max_queue_size )


h1.setIP('10.0.1.1', intf='h1-eth0')
h1.setIP('10.0.1.2', intf='h1-eth1')

h2.setIP('10.0.2.1', intf='h2-eth0')
h2.setIP('10.0.2.2', intf='h2-eth1')

net.start()

time.sleep(1) # wait for net to startup (unless this, it might won't work...)


print "\n"," "*5,"#"*40,"\n"," "*10,"STARTING\n"


if capture_mptcp_headers:
	print 'starting capturing...',
	print h2.cmd('tshark -f "tcp" -i any -a duration:'+str(test_duration+1)+' -T pdml '+
					' | sed -e "s/30313233343536373839//g" '+			# remove unimportant test data, generated by iperf
					' | sed -e "s/30:31:32:33:34:35:36:37:38:39://g" '+
					' >capt.txt &'),
	time.sleep(1) # wait for tshark to startup
	print '...capture started\n'

def under_testing():
	time.sleep(test_duration/3.0)
	if cut_a_link:
		print "\n",'cutting link...',
		print h1.intf('h1-eth0').ifconfig('down'),
		print 'link down\n'
	time.sleep(test_duration/3.0)
	if add_a_link:
		print 'adding a new link...',
		net.addLink( h1, s3, cls=TCLink , bw=50, delay='1ms', max_queue_size=max_queue_size )
		s3.attach('s3-eth5')
		h1.setIP('10.0.1.3', intf='h1-eth2')
		print 'link added\n'
	time.sleep(test_duration/3.0)
	
	time.sleep(5) # wait (a bit) to finish

test_started_timestamp = time.time()

if test_bandwith:
	print 'starting iperf server at',h2.IP()
	h2.cmd('iperf -s -i 0.5 > iperf_bandwith_server_log.txt & ') # server
	
	print 'starting iperf client at',h1.IP(),', connect to ',h2.IP()
	h1.cmd('iperf -t '+str(test_duration)+' -i 0.5 -c '+h2.IP()+' > iperf_bandwith_client_log.txt &') # cliens
	
	under_testing()
	
	print "\niperf client response:"
	print h1.cmd('cat iperf_bandwith_client_log.txt')
	
	print "\niperf server response:"
	print h2.cmd('cat iperf_bandwith_server_log.txt')

if capture_mptcp_headers:
	try:
		time.sleep(0.5)
		packets_ip_stat = {}
		# parse result
		capture_data = h1.cmd('cat capt.txt')
		capture_data = capture_data[ capture_data.find('<pdml') : ]
		capture_data = re.findall( r"<packet>.+?</packet>", capture_data, re.DOTALL)
		print "capturing ended, result ("+str(len(capture_data))+"):"
		for i in capture_data:
			packet = xml.etree.ElementTree.fromstring(i)
			packet_timestamp = packet.find('proto[@name="geninfo"]').find('field[@name="timestamp"]').get('value')
			ip_header = packet.find('proto[@name="ip"]')
			tcp_header = packet.find('proto[@name="tcp"]')
			src_ip = ip_header.find('field[@name="ip.src"]').get('show')
			dst_ip = ip_header.find('field[@name="ip.dst"]').get('show')
			src_port = tcp_header.find('field[@name="tcp.srcport"]').get('show')
			dst_port = tcp_header.find('field[@name="tcp.dstport"]').get('show')
			stat_key = src_ip+':'+src_port+' - '+dst_ip+':'+dst_port
			packets_ip_stat[stat_key] = 0 if (stat_key not in packets_ip_stat) else packets_ip_stat[stat_key]+1
			package_info = ("%.2f" % (float(packet_timestamp)-test_started_timestamp)) +"\t"+src_ip+':'+src_port+"\t->\t"+dst_ip+':'+dst_port+"\t"
			allmptcp = tcp_header.findall('field[@name="tcp.options"]/*/field[@name="tcp.option_kind"][@show="30"]/..')
			mptcp_subtypes = []
			for mptcp in allmptcp:
				package_info = package_info + mptcp.get('show') + "\t"
				mptcp_subtype = mptcp.find('field[@name="tcp.options.mptcp.subtype"]').get('value')
				mptcp_subtypes.append( mptcp_subtype )
				package_info = package_info + '(subtype: '+mptcp_subtype
				if mptcp_subtype == '1': # Join connection
					addrid = mptcp.find('field[@name="tcp.options.mptcp.addrid"]')
					if addrid != None:
						package_info = package_info + ', addrid: '+addrid.get('value')
				if mptcp_subtype == '3': # Add Address
					addrid = mptcp.find('field[@name="tcp.options.mptcp.addrid"]')
					if addrid != None:
						package_info = package_info + ', addrid: '+addrid.get('value')
					newaddripv4 = mptcp.find('field[@name="tcp.options.mptcp.ipv4"]')
					if newaddripv4 != None:
						package_info = package_info + ', ipv4: '+newaddripv4.get('show')
				package_info = package_info + ' )' + "\t"
			if len(mptcp_subtypes)==0 or ( len(mptcp_subtypes)==1 and mptcp_subtypes[0]=='2' ):
				continue # skip packet contains only data, not interesting
			print package_info
			#xml.etree.ElementTree.dump(mptcp)
		print "\npackets count stat:\n",",\n".join([ (i+' : '+str(packets_ip_stat[i])) for i in sorted(packets_ip_stat.keys())])
	except Exception as e:
		print "\n\nERROR:",e,"\n\n"


net.stop()

print

